In [1]:
import pandas as pd

In [3]:
# csv 파일 불러오기
# csv 파일을 불러와서 데이터 프레임을 생성

df = pd.read_csv('./input/weather.csv')
df

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [4]:
print(df)

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [5]:
# shape 속성을 이용하면 데이터의 (행, 열) 크기를 확인할 수 있음.

# 행, 열 크기 확인하기
df.shape

(3653, 4)

In [7]:
# info()메서드는 데이터에 대한 전반적인 정보를 나타냄
# df를 구성하는 행과 열의 크기, 컬럼명, 컬럼을 구성하는 값의 자료형을 출력해줌.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3653 entries, 0 to 3652
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       3653 non-null   object
 1   temp       3653 non-null   float64
 2   max_wind   3649 non-null   float64
 3   mean_wind  3647 non-null   float64
dtypes: float64(3), object(1)
memory usage: 114.3+ KB

In [ ]:
# 전체 행 (데이터의 수) 확인 가능 : RangeIndex: 3653 entries, 0 to 3652
# 3653 entries 데이터의 수
# csv의 모듈로 읽었으면 숫자도 모두 object로 읽었겠지만 pandas를 사용함으로써 숫자는 float으로 처리함

# 데이터 타입 확인 가능 : dtypes: float64(3), object(1)
# 실수 float가 3개, 문자열 object이 1개

# 결측치 확인 가능 : 전체 행 - Non-Null Count
# max_wind, mean_wind 변수에 결측치가 있음

# memory usage: 114.3+ KB
# 메모리 사용량

In [10]:
# 데이터를 잘 불러 왔는지 

# 상위 n행 살펴보기
df.head(10)

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6
5  2010-08-06  26.8       9.8        8.0
6  2010-08-07  27.5       9.1        5.0
7  2010-08-08  26.6       5.9        4.0
8  2010-08-09  26.9       5.1        3.1
9  2010-08-10  25.6      10.2        5.5

In [12]:
# 하위 n행 살펴보기
df.tail(20)

            date  temp  max_wind  mean_wind
3633  2020-07-12  18.9       5.5        2.4
3634  2020-07-13  17.8      10.3        4.6
3635  2020-07-14  17.8      12.7        9.4
3636  2020-07-15  17.8       6.5        3.4
3637  2020-07-16  19.3       3.5        1.8
3638  2020-07-17  20.1       3.3        2.0
3639  2020-07-18  20.6       3.5        1.4
3640  2020-07-19  21.1       4.9        1.7
3641  2020-07-20  23.0      11.2        7.3
3642  2020-07-21  24.0       5.3        2.0
3643  2020-07-22  22.2       4.3        1.9
3644  2020-07-23  21.5       4.9        2.3
3645  2020-07-24  20.4       7.2        2.8
3646  2020-07-25  20.7       3.8        1.1
3647  2020-07-26  21.4       4.8        2.8
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

In [13]:
# head()는 상위 5개의 행을 출력하고, tail()은 하위 5개 행을 출력함
# 괄호() 안에 원하는 숫자를 넣으면 그 숫자만큼 행을 출력

In [14]:
# 인덱스(행 이름)과 열의 레이블(칼럼 이름)을 출력할 때 사용

# 인덱스 출력
df.index
# 데이터프레임의 인덱스(행 이름)을 반환. 인덱스를 따로 지정하지 않았기 때문에 0부터 시작하는 인덱스가 부여

RangeIndex(start=0, stop=3653, step=1)

In [15]:
# 컬럼 출력
df.columns

Index(['date', 'temp', 'max_wind', 'mean_wind'], dtype='object')

In [16]:
# 해당 데이터프레임을 구성하는 컬럼명을 확인할 수 있음
# 컬럼명을 변경할 때도 유용하게 사용

In [17]:
# describe
# 데이터의 컬럼별 요약 통계량을 나타냄
# 또한 mean(), max() 등 개별 함수를 사용하여 통계량을 계산할 수 있음

# 요약 통계량 확인하기
df.describe()

              temp     max_wind    mean_wind
count  3653.000000  3649.000000  3647.000000
mean     12.942102     7.911099     3.936441
std       8.538507     3.029862     1.888473
min      -9.000000     2.000000     0.200000
25%       5.400000     5.700000     2.500000
50%      13.800000     7.600000     3.600000
75%      20.100000     9.700000     5.000000
max      31.300000    26.000000    14.900000

In [21]:
# sort_values 형식
# DataFrame.sort_values(by=['정렬변수1', '정렬변수2',...], ascending=True, inplace=False)
# by=[] : by는 사용하지 않아도 됨
# ascending=True : True가 기본값이고 오름차순 정렬, 내림차순 정렬일 경우에는 False를 사용
# inplace=False : True면 정렬 결과가 동일 데이터프레임 이름으로 저장. 기본값은 False.

df.sort_values(by=['max_wind'], ascending=False, inplace=False)

            date  temp  max_wind  mean_wind
2988  2018-10-06  19.4      26.0        7.0
3340  2019-09-23  15.0      25.8       11.0
1850  2015-08-25  20.1      25.3       14.9
3339  2019-09-22  15.7      23.1       11.9
1851  2015-08-26  17.4      22.6        8.1
...          ...   ...       ...        ...
1514  2014-09-23  20.7       2.0        1.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

[3653 rows x 4 columns]

In [22]:
# value_counts
# 범주형 변수의 빈도분석 결과를 출력. 즉, 어떤 컬럼의 unique value(고유값)들의 개수를 구함

bank = pd.read_csv('./input/bank.csv')
bank.head()

           job  education  balance  duration   y
0   management   tertiary     2143       261  no
1   technician  secondary      265       348  no
2  blue-collar  secondary       -7       365  no
3   technician  secondary       -3      1666  no
4   technician  secondary     -103       145  no

In [26]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7234 entries, 0 to 7233
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   job        7190 non-null   object
 1   education  6961 non-null   object
 2   balance    7234 non-null   int64
 3   duration   7234 non-null   int64
 4   y          7234 non-null   object
dtypes: int64(2), object(3)
memory usage: 282.7+ KB

In [27]:
# 빈도 분석 출력하기

bank['job'].value_counts()

job
management       1560
blue-collar      1499
technician       1206
admin.            834
services          661
retired           351
self-employed     256
entrepreneur      239
unemployed        223
housemaid         208
student           153
Name: count, dtype: int64

In [28]:
bank['education'].value_counts()

education
secondary    3745
tertiary     2178
primary      1038
Name: count, dtype: int64

In [29]:
bank['balance'].value_counts() # 범주형이 아니라도 사용 가능하긴 함. <-> sort_values

balance
 0       563
 1        31
 4        28
 2        22
 3        19
        ...
-37        1
-180       1
 2099      1
 3735      1
 6403      1
Name: count, Length: 3102, dtype: int64

In [31]:
bank['job'].value_counts(ascending=True)

job
student           153
housemaid         208
unemployed        223
entrepreneur      239
self-employed     256
retired           351
services          661
admin.            834
technician       1206
blue-collar      1499
management       1560
Name: count, dtype: int64

In [37]:
# unique
# 데이터가 무엇으로 구성되어 있는지 보고싶을 때 사용. 열의 고유값을 볼 수 있음

# column의 고유값 출력하기
bank['job'].unique()

array(['management', 'technician', 'blue-collar', 'retired', 'services',
       'admin.', 'entrepreneur', 'self-employed', 'unemployed', 'student',
       nan, 'housemaid'], dtype=object)

In [35]:
bank['job'].unique().size

12

In [36]:
bank['y'].unique()

array(['no', 'yes'], dtype=object)