In [ ]:
# Pandas는 누락된 데이터를 표시할 때 NaN(Not a Number)으로 표기하며, 연산에는 포함되지 않음

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('./input/weather.csv')
df.head()

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6

In [4]:
df.index

RangeIndex(start=0, stop=3653, step=1)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3653 entries, 0 to 3652
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       3653 non-null   object
 1   temp       3653 non-null   float64
 2   max_wind   3649 non-null   float64
 3   mean_wind  3647 non-null   float64
dtypes: float64(3), object(1)
memory usage: 114.3+ KB

In [6]:
# 결측 데이터 확인
# 최고풍속이 측정되지 않은 모든 데이터 출력
# isna() 매서드는 값이 NaN일때 True, 아닌 경우엔 False를 반환
nan_rows = df['max_wind'].isna()
nan_rows

0       False
1       False
2       False
3       False
4       False
        ...
3648    False
3649    False
3650    False
3651    False
3652    False
Name: max_wind, Length: 3653, dtype: bool

In [7]:
df[nan_rows]

            date  temp  max_wind  mean_wind
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

In [8]:
df[df['mean_wind'].isna()]

            date  temp  max_wind  mean_wind
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
1694  2015-03-22  10.1      11.6        NaN
1704  2015-04-01   7.3      12.1        NaN
3182  2019-04-18  15.7      11.7        NaN

In [9]:
df[df['mean_wind'].isnull()]

            date  temp  max_wind  mean_wind
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
1694  2015-03-22  10.1      11.6        NaN
1704  2015-04-01   7.3      12.1        NaN
3182  2019-04-18  15.7      11.7        NaN

In [ ]:
# isnull()은 결측 데이터이면 True반환, 유효한 데이터가 존재하면 False반환
# isna(), isnull()은 기능적으로 동일

In [10]:
# 결측 데이터 개수 확인
print(nan_rows.sum())

4

In [11]:
print(df['mean_wind'].isna().sum())

6

In [12]:
df.isna()

       date   temp  max_wind  mean_wind
0     False  False     False      False
1     False  False     False      False
2     False  False     False      False
3     False  False     False      False
4     False  False     False      False
...     ...    ...       ...        ...
3648  False  False     False      False
3649  False  False     False      False
3650  False  False     False      False
3651  False  False     False      False
3652  False  False     False      False

[3653 rows x 4 columns]

In [13]:
df.isna().sum()

date         0
temp         0
max_wind     4
mean_wind    6
dtype: int64

In [14]:
# notnull()은 유효한 데이터가 존재하면 True반환, 결측 데이터면 False 반환
df.notnull().sum()

date         3653
temp         3653
max_wind     3649
mean_wind    3647
dtype: int64

In [ ]:
# 2. 결측 데이터 삭제하기
# 결측 데이터를 다루는 가장 간단한 방법은 결측 데이터를 가진 행이나 열을 삭제.
# 판다스에서 dropna()를 이용하여 삭제 할 수 있음.

# DataFrame.dropna(axis, how, thresh, subset, inplace)
# axis : 축을 행 또는 열로 결정
# 0 또는 'index'이면 누락된 값이 포함된 행을 삭제
# 1 또는 'columns'이면 누락된 값이 포함된 열을 삭제
# 기본적으로 값은 0
# how : any는 null 값이 있는 경우 행 또는 열을 삭제
# all은 모든 값이 누락된 경우 행 또는 열을 삭제
# 기본값은 any
# inplace : 데이터프레임에 나온 값을 저장할 것인지를 설정하는 변수로 기본적으로 값은 False

In [15]:
# 결측 데이터가 있는 행 삭제 후 확인
df.isna().sum()

date         0
temp         0
max_wind     4
mean_wind    6
dtype: int64

In [16]:
df1 = df.dropna() # 옵션을 지정하지 않아서 행기준, NaN가 하나라도 있는 경우에 삭제
df1.isna().sum()

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64

In [17]:
df.dropna(axis=1).isna().sum()

date    0
temp    0
dtype: int64

In [18]:
# 결측 데이터 대체하기 : 평균값으로 대체
# fillna() 결측 데이터를 특정 값으로 채움. inplace를 True로 설정해 원본 데이터를 수정
df.fillna({'max_wind': df['max_wind'].mean()}, inplace=True)
df.fillna({'mean_wind': df['mean_wind'].mean()}, inplace=True)

In [19]:
df.isna().sum()

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64