In [1]:
import pandas as pd

In [2]:
# 1. 표 형식의 데이터 파일을 읽기

In [3]:
# 판다스에서 csv파일을 읽을 때는 read_csv() 메서드 사용
# DataFrame_data = pd.read_csv(file_name [, options])

In [4]:
pd.read_csv('./input/sea_rain1.csv')

     연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [5]:
df1 = pd.read_csv('./input/sea_rain1.csv')
df1.head()

     연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [6]:
df1.dtypes

연도      int64
동해    float64
남해    float64
서해    float64
전체    float64
dtype: object

In [9]:
# 파이썬에서 텍스트파일을 생성하면 기본 문자 인코딩이 'utf-8'이고, 메모장의 경우 기본 문자 인코딩이 'cp949'
# sea_rain1_from_notepad.csv 파일의 경우 메모장으로 생성해서, 인코딩이 'cp949'이므로 에러가 남
pd.read_csv('./input/sea_rain1_from_notepad.csv', encoding='cp949')

     연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [11]:
# sep : 나누기(seperate)
pd.read_csv('./input/sea_rain1_space.txt', sep=' ')

     연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [13]:
# read_csv()로 텍스트 파일을 읽어오면 index가 자동으로 지정
# 이때 자동으로 생성된 index 말고 데이터 파일에서 특정 열 column을 index로  선택하려면 'index_col=열 이름'을 추가
pd.read_csv('./input/sea_rain1.csv', index_col='연도')

           동해       남해       서해       전체
연도
1996  17.4629  17.2288  14.4360  15.9067
1997  17.4116  17.4092  14.8248  16.1526
1998  17.5944  18.0110  15.2512  16.6044
1999  18.1495  18.3175  14.8979  16.6284
2000  17.9288  18.1766  15.0504  16.6178

In [14]:
# 표 형식의 데이터를 파일로 쓰기

In [15]:
# to_csv를 이용하면 DataFrame 형식의 데이터를 텍스트 (csv) 파일로 저장
# DataFrame_data.to_csv(file_name [, options])
# file_name은 텍스트 파일 이름으로 경로를 포함할 수 있음.
# 선택사항인 options에는 구분자와 문자의 인코딩 방식 등을 지정할 수 있고, 지정하지 않으면 구분자는 콤마가 되고, 문자의 인코딩 방식은 'utf-8'이 됨

In [16]:
# 네명의 몸무게 weight와 키 Height 데이터를 DataFrame 형식으로 생성
df_WH = pd.DataFrame({'Weight': [62, 67, 55, 74],
                      'Height': [165, 177, 160, 180]},
                     index=['ID_1', 'ID_2', 'ID_3', 'ID_4'])
df_WH

      Weight  Height
ID_1      62     165
ID_2      67     177
ID_3      55     160
ID_4      74     180

In [18]:
df_WH.index.name = 'User'
df_WH

      Weight  Height
User
ID_1      62     165
ID_2      67     177
ID_3      55     160
ID_4      74     180

In [19]:
# 파일로 저장하기 전에 몸무게와 키를 이용해 체질량 지수 BMI를 구해서 추가
# 체질량 지수 Body Mass Index는 몸무게(KG)과 키(m)를 이용해 측정
# BMI = W / H^2

In [20]:
# 키의 경우 데이터가 cm 단위라서 m 단위로 변경
BMI = df_WH['Weight'] / ((df_WH['Height'] / 100) ** 2)
BMI

User
ID_1    22.773186
ID_2    21.385936
ID_3    21.484375
ID_4    22.839506
dtype: float64

In [21]:
# 체질량 지수를 df_WH에 추가
df_WH['BMI'] = BMI
df_WH

      Weight  Height        BMI
User
ID_1      62     165  22.773186
ID_2      67     177  21.385936
ID_3      55     160  21.484375
ID_4      74     180  22.839506

In [22]:
df_WH.to_csv('./output/user_bmi.csv')

In [23]:
# DataFrame 데이터를 파일로 저장할 때 옵션을 지정하는 예
# 한 회사의 제품별 판매 가격과 판매량 정보가 있는 DataFrame 데이터를 생성,
df_pr = pd.DataFrame({'판매가격': [2000, 3000, 5000, 10000],
                      '판매량': [32, 53, 40, 25]},
                      index=['P1001', 'P1002', 'P1003', 'P1004'])
df_pr.index.name = '제품번호'
df_pr

        판매가격  판매량
제품번호
P1001   2000   32
P1002   3000   53
P1003   5000   40
P1004  10000   25

In [24]:
df_pr.to_csv('./output/tmp.csv', encoding='cp949')