In [1]:
import pandas as pd

In [3]:
# 엑셀 파일 dust1.xlxs 파일을 불러와서 데이터프레임을 생성
df = pd.read_excel('./input/dust1.xlsx')
df.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      32 non-null     object
 1   망       32 non-null     object
 2   측정소코드   32 non-null     int64
 3   측정소명    32 non-null     object
 4   측정일시    32 non-null     int64
 5   SO2     32 non-null     float64
 6   CO      32 non-null     float64
 7   O3      32 non-null     float64
 8   NO2     32 non-null     float64
 9   PM10    32 non-null     int64
 10  PM25    32 non-null     int64
 11  주소      32 non-null     object
dtypes: float64(4), int64(4), object(4)
memory usage: 3.1+ KB

In [5]:
df.isnull().sum()

지역       0
망        0
측정소코드    0
측정소명     0
측정일시     0
SO2      0
CO       0
O3       0
NO2      0
PM10     0
PM25     0
주소       0
dtype: int64

In [6]:
# 컬럼(변수) 삭제/생성하기
# 데이터 분석에 필요없는 '지역', '망', '측정소코드' 컬럼을 삭제하고 특정값으로 새로운 컬럼을 생성
dust = df.drop(['지역', '망', '측정소코드'], axis=1)
# axis의 기본값이 axis=0으로 행 삭제가 됨. 컬럼을 삭제하기 위해서는 axis=1을 반드시 사용
dust.head()

  측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소
0  송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236
1  송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236
2  송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236
3  송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236
4  송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236

In [7]:
# 새로운 컬럼 생성
dust['city'] = '서울'
dust.head()

,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소,city
0,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,서울
1,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,서울
2,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,서울
3,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,서울
4,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,서울

In [8]:
# 2. 컬럼 이름 변경
# 1) DataFrame.columns=['새이름1', '새이름2', ...]
# 전체 변수 이름을 재설정
# 변수명을 차례대로 재설정. 변수가 많은 경우 적절하지 않음
# 2) DataFrame.rename(columns={'기존이름':'새이름'}, inplace=True)
# 원하는 변수이름만 수정
# 딕셔너리 구조로 정의. 즉 이전 열이름을 키로 지정하고 새이름으로 값으로 지정

In [9]:
dust.rename(columns={'측정소명' : 'name', '측정일시' : 'date', '주소' : 'address'}, inplace=True)
dust.head()

,name,date,SO2,CO,O3,NO2,PM10,PM25,address,city
0,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,서울
1,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,서울
2,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,서울
3,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,서울
4,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,서울

In [10]:
dust.columns

Index(['name', 'date', 'SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25', 'address',
       'city'],
      dtype='object')

In [11]:
# 3. 데이터 형변환
dust.dtypes

name        object
date         int64
SO2        float64
CO         float64
O3         float64
NO2        float64
PM10         int64
PM25         int64
address     object
city        object
dtype: object

In [13]:
# date 컬럼이 숫자형(int)로 저장되어 있음.
# 숫자 형식은 문자 형식으로 변환
# astype(str)으로 문자열 형식으로 변환하고 데이터 길이를 날짜 형식 8자리에 적합하도록 str.slice()를 사용하여 첫 8자리만 저장
# 문자열 데이터를 숫자 형식으로 바꾸는 경우는 .astype(int)사용

# 숫자 int형을 문자열로 변환
dust['date'] = dust['date'].astype('str')
dust.head()

,name,date,SO2,CO,O3,NO2,PM10,PM25,address,city
0,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,서울
1,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,서울
2,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,서울
3,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,서울
4,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,서울

In [14]:
dust['date'] = dust['date'].str.slice(0, 8)
dust.head()

  name      date    SO2   CO     O3    NO2  PM10  PM25           address city
0  송파구  20210401  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236   서울
1  송파구  20210401  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236   서울
2  송파구  20210401  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236   서울
3  송파구  20210401  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236   서울
4  송파구  20210401  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236   서울

In [16]:
dust.dtypes

name        object
date        object
SO2        float64
CO         float64
O3         float64
NO2        float64
PM10         int64
PM25         int64
address     object
city        object
dtype: object

In [17]:
# 문자 형식을 날짜형으로 변환
dust['date'] = pd.to_datetime(dust['date'])
dust.head()

  name       date    SO2   CO     O3    NO2  PM10  PM25           address city
0  송파구 2021-04-01  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236   서울
1  송파구 2021-04-01  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236   서울
2  송파구 2021-04-01  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236   서울
3  송파구 2021-04-01  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236   서울
4  송파구 2021-04-01  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236   서울

In [18]:
dust.dtypes

name               object
date       datetime64[ns]
SO2               float64
CO                float64
O3                float64
NO2               float64
PM10                int64
PM25                int64
address            object
city               object
dtype: object

In [19]:
# 날짜 형식 활용 : Series.dt 형식

dust['year'] = dust['date'].dt.year
dust['month'] = dust['date'].dt.month
dust['day'] = dust['date'].dt.day
dust.head()

,name,date,SO2,CO,O3,NO2,PM10,PM25,address,city,year,month,day
0,송파구,2021-04-01,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,서울,2021,4,1
1,송파구,2021-04-01,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,서울,2021,4,1
2,송파구,2021-04-01,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,서울,2021,4,1
3,송파구,2021-04-01,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,서울,2021,4,1
4,송파구,2021-04-01,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,서울,2021,4,1