In [1]:
# 판다스 데이터 그룹핑하기
# 데이터 그룹핑은 데이터를 특정한 값에 기반해 묶는 기능으로 groupby()를 사용하여 통계량을 요약할 수 있음
# 통계량에 관계된 매서드에는 mean, std, var,max,min 등이 있음/

In [3]:
import pandas as pd

df = pd.read_excel('./input/nation.xlsx')
df

  국적코드  성별    입국객수    증가수
0  A01  남성  125000   8000
1  A01  여성  130000  10000
2  A05  남성     300     10
3  A05  여성     200     50
4  A06  남성  158912  24486
5  A06  여성  325000  63466

In [4]:
# 1. 한 열을 기준으로 그룹화하기
df.groupby('국적코드').sum()

        성별    입국객수    증가수
국적코드
A01   남성여성  255000  18000
A05   남성여성     500     60
A06   남성여성  483912  87952

In [5]:
df.groupby('성별').sum()

         국적코드    입국객수    증가수
성별
남성  A01A05A06  284212  32496
여성  A01A05A06  455200  73516

In [6]:
# groupby()를 사용하여 '국적코드' 열을 기준으로 그룹화하고, sum() 매서드를 적용

In [7]:
# 2. 여러 열을 기준으로 그룹화하기
df.groupby(['국적코드', '성별']).sum()

           입국객수    증가수
국적코드 성별
A01  남성  125000   8000
     여성  130000  10000
A05  남성     300     10
     여성     200     50
A06  남성  158912  24486
     여성  325000  63466

In [8]:
df.groupby(['성별', '국적코드']).sum()

           입국객수    증가수
성별 국적코드
남성 A01   125000   8000
   A05      300     10
   A06   158912  24486
여성 A01   130000  10000
   A05      200     50
   A06   325000  63466

In [9]:
df.groupby(['성별', '국적코드']).mean()

             입국객수      증가수
성별 국적코드
남성 A01   125000.0   8000.0
   A05      300.0     10.0
   A06   158912.0  24486.0
여성 A01   130000.0  10000.0
   A05      200.0     50.0
   A06   325000.0  63466.0

In [10]:
df.groupby('국적코드')[['입국객수', '증가수']].mean()

          입국객수      증가수
국적코드
A01   127500.0   9000.0
A05      250.0     30.0
A06   241956.0  43976.0

In [12]:
df1 = df.groupby(['성별', '국적코드']).sum()
df1

           입국객수    증가수
성별 국적코드
남성 A01   125000   8000
   A05      300     10
   A06   158912  24486
여성 A01   130000  10000
   A05      200     50
   A06   325000  63466

In [13]:
df1.index

MultiIndex([('남성', 'A01'),
            ('남성', 'A05'),
            ('남성', 'A06'),
            ('여성', 'A01'),
            ('여성', 'A05'),
            ('여성', 'A06')],
           names=['성별', '국적코드'])

In [14]:
df1.loc[('여성', 'A01'), '증가수']

np.int64(10000)