In [1]:
# 데이터 통합하기

In [2]:
# 두개의 데이터를 하나로 통합하는 방법
# 1) 세로로 증가하는 방향으로 통합하기
# 2) 가로로 증가하는 방향으로 통합하기
# 3) 특정 열을 기준으로 통합하는 방법

In [3]:
# 1. 세로 방향으로 통합하기
# DataFrame에서 columns가 같은 두 데이터를 세로 방향(index 증가 방향)으로 합하려면 append()를 이용
# DataFrame_data1.append(DataFrame_data2 [,ignore_index=True])

# 세로 방향으로 DataFrame_date1 다음에 DataFrame_data2가 추가돼서 DataFrame 데이터로 반환
# 'ignore_index=False'를 입력하지 않으면 생성된 DataFrame 데이터에는 기존의 데이터의 index가 그대로 유지
# 'ignore_index=True'를 입력하면 생성된 DataFrame 데이터에는 데이터 순서대로 새로운 index가 할당

# frame.append() 에서 pandas.concat() 사용으로 수정

In [3]:
import pandas as pd

In [5]:
# 두 학급의 시험 점수가 담긴 DataFrame을 생성
df1 = pd.DataFrame({'Class1':[95, 92, 98, 100],
                    'Class2':[91, 93, 97, 99]})
df1

   Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99

In [6]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
# 각 반에 각각 두 명의 학생이 전학을 와서 DataFrame 추가 생성
df2 = pd.DataFrame({'Class1':[87, 89],
                    'Class2':[85, 90]})
df2

   Class1  Class2
0      87      85
1      89      90

In [8]:
df2.index

RangeIndex(start=0, stop=2, step=1)

In [9]:
df_concat = pd.concat([df1, df2])
df_concat

   Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
0      87      85
1      89      90

In [10]:
df_concat.index # rangeindex가 아님

Index([0, 1, 2, 3, 0, 1], dtype='int64')

In [11]:
# 기존의 index가 유지되어서 중복된 index가 있음
# 생성된 데이터에서 순차적으로 index가 증가하게 하려면 옵션으로 ignore_index=True을 사용
df_concat = pd.concat([df1, df2], ignore_index=True)
df_concat

   Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
4      87      85
5      89      90

In [12]:
df_concat.index # rangeindex

RangeIndex(start=0, stop=6, step=1)

In [14]:
# 만약 columns가 같지 않은 DataFrame 데이터를 concat()를 이용해 추가한다면 데이터가 없는 부분은 NaN으로 채워짐
df3 = pd.DataFrame({'Class1':[96, 83]})
df3

   Class1
0      96
1      83

In [15]:
pd.concat([df1, df3], ignore_index=True)

   Class1  Class2
0      95    91.0
1      92    93.0
2      98    97.0
3     100    99.0
4      96     NaN
5      83     NaN

In [1]:
# 2. 가로방향으로 통합하기
# index가 같은 두 DataFrame 데이터에 대해 가로 방향 (columns 증가 방향)에 새로운 데이터를 추가할 때는 join()을 이용.
# DataFrame_data1.join(DataFrame_data2)
# DataFrame_data1 다음에 가로 방향으로 DataFrame_data2가 추가돼서 DataFrame 데이터로 반환.

In [4]:
df1 = pd.DataFrame({'Class1':[95, 92, 98, 100],
                    'Class2':[91, 93, 97, 99]})
df1

   Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99

In [5]:
df2 = pd.DataFrame({'Class3':[93, 91, 95, 98]})
df2

   Class3
0      93
1      91
2      95
3      98

In [6]:
df1.join(df2)

   Class1  Class2  Class3
0      95      91      93
1      92      93      91
2      98      97      95
3     100      99      98

In [7]:
# index 라벨을 지정한 DataFrame의 데이터의 경우에도 index가 같으면 join()을 이용해 가로방향으로 데이터를 추가할 수 있음
index_label = ['a', 'b', 'c', 'd']
df3 = pd.DataFrame({'Class1':[95, 92, 98, 100],
                    'Class2':[91, 93, 97, 99]}, index=index_label)
df4 = pd.DataFrame({'Class3':[93, 91, 95, 98]}, index=index_label)
df3

   Class1  Class2
a      95      91
b      92      93
c      98      97
d     100      99

In [8]:
df3.join(df4)

   Class1  Class2  Class3
a      95      91      93
b      92      93      91
c      98      97      95
d     100      99      98

In [9]:
# 만약 index의 크기가 다른 DataFrame 데이터를 join()을 이용해 추가한다면 데이터가 없는 부분은 NaN으로 채워짐
df5 = pd.DataFrame({'Class4': [82, 92]})
df5

   Class4
0      82
1      92

In [10]:
df1.join(df5)

   Class1  Class2  Class4
0      95      91    82.0
1      92      93    92.0
2      98      97     NaN
3     100      99     NaN

In [11]:
# 3) 특정 열을 기준으로 통합하기
# 두 개의 DataFrame 데이터를 특정 열을 기준으로 통합할 때는 특정 열을 키(key) 이용.
# 만약 두 개의 DataFrame 데이터에 공통된 열이 있다면 이 열을 기준으로 두 데이터를 통합하는 경우.
# DataFrmae_left_data.merge(DataFrame_right_data)
# 왼쪽 데이터 DataFrmae_left_data와 오른쪽 데이터 DataFrame_right_data가 공통된 열 key을 중심으로 좌우로 통합.

In [12]:
df_A_B = pd.DataFrame({'판매월': ['1월', '2월', '3월', '4월'],
                       '제품A': [100, 150, 200, 130],
                       '제품B': [90, 110, 140, 170]})
df_A_B

  판매월  제품A  제품B
0  1월  100   90
1  2월  150  110
2  3월  200  140
3  4월  130  170

In [13]:
df_C_D = pd.DataFrame({'판매월': ['1월', '2월', '3월', '4월'],
                       '제품C': [112, 141, 293, 134],
                       '제품D': [90, 110, 140, 170]})
df_C_D

  판매월  제품C  제품D
0  1월  112   90
1  2월  141  110
2  3월  293  140
3  4월  134  170

In [14]:
# df_A_B와 df_C_D에 모두 있는 것이 '판매월'인 열 데이터이므로 이를 중심으로 두 DataFrame 데이터를 통합
df_A_B.merge(df_C_D)

  판매월  제품A  제품B  제품C  제품D
0  1월  100   90  112   90
1  2월  150  110  141  110
2  3월  200  140  293  140
3  4월  130  170  134  170

In [15]:
# 두 데이터가 '판매월'을 기준으로 통합된 결과. 특정 열을 기준으로 두 DataFrame 데이터가 모두 값을 갖고 있을 때 득정 열을 기준으로 통합

ValueError: columns overlap but no suffix specified: Index(['판매월'], dtype='object')

In [16]:
# 두 개의 DataFrame 데이터가 특정 열을 기준으로 일부만 공통된 값을 갖는 경우에 통합하려면 merge()에 선택 인자를 지정.
# DataFrmae_left_data.merge(DataFrame_right_data, how=merge_method, on=key_label)
# on 인자에는 통합하려는 기준이 되는 특정 열 key의 라벨 이름 key_label을 입력.
# on 인자를 입력하지 않으면 자동으로 두 데이터에서 공통적으로 포함된 열이 선택.
# how 인자에는 지정된 특정 열 key을 기준으로 통합방법 merge_method을 지정.

# merge()함수의 how 선택 인자에 따른 통합 방법.
# left : 왼쪽 데이터는 모두 선택하고 지정된 열 key에 값이 있는 오른쪽 데이터를 선택.
# right : 오른쪽 데이터는 모두 선택하고 지정된 열 key에 값이 있는 왼쪽 데이터를 선택.
# outer : 지정된 열 key을 기준으로 왼쪽과 오른쪽 데이터를 모두 선택.
# inner : 지정된 열 key을 기준으로 왼쪽과 오른쪽 데이터 중 공통 항목만 선택. (기본값)

In [17]:
df_left = pd.DataFrame({'key': ['A', 'B', 'C'],
                        'left': [1, 2, 3]})
df_left

  key  left
0   A     1
1   B     2
2   C     3

In [18]:
df_right = pd.DataFrame({'key': ['A', 'B', 'D'],
                        'right': [4, 5, 6]})
df_right

  key  right
0   A      4
1   B      5
2   D      6

In [20]:
df_left.merge(df_right) # df_left.merge(df_right, how='inner'), default값이 inner

  key  left  right
0   A     1      4
1   B     2      5

In [19]:
# 해당 항목에 데이터가 없는 경우 NaN로 저장
df_left.merge(df_right, how='left', on='key')

  key  left  right
0   A     1    4.0
1   B     2    5.0
2   C     3    NaN

In [21]:
df_left.merge(df_right, how='right', on='key')

  key  left  right
0   A   1.0      4
1   B   2.0      5
2   D   NaN      6

In [22]:
df_left.merge(df_right, how='outer', on='key')

  key  left  right
0   A   1.0    4.0
1   B   2.0    5.0
2   C   3.0    NaN
3   D   NaN    6.0