In [1]:
import pandas as pd

In [8]:
df = pd.read_excel('./input/vaccine.xlsx')
df.tail()

,date,subject,day1num,day1sum,day1rate,day2num,day2sum,day2rate
174,2021.04.25,1023346,23323,350631,34.2,3411,18513,1.8
175,2021.04.24,1023346,200,350427,34.2,0,18513,1.8
176,2021.04.23,1027740,10195,345764,33.6,119,18376,1.8
177,2021.04.22,1023538,27074,317386,31.0,2479,15901,1.6
178,2021.04.21,1019322,22501,291857,28.6,2358,13543,1.3

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      179 non-null    object
 1   subject   179 non-null    int64
 2   day1num   179 non-null    int64
 3   day1sum   179 non-null    int64
 4   day1rate  179 non-null    float64
 5   day2num   179 non-null    int64
 6   day2sum   179 non-null    int64
 7   day2rate  179 non-null    float64
dtypes: float64(2), int64(5), object(1)
memory usage: 11.3+ KB

In [5]:
# 필요없는 열을 삭제한 후 출력
# 삭제할 열 : day1sum, day1rate, day2sum, day2rate
df1 = df.drop(columns=['day1sum', 'day1rate', 'day2sum', 'day2rate'])
df1.head()

         date  subject  day1num  day2num
0  2021.10.16  9505868    10673    66910
1  2021.10.15  9505868    14556   133580
2  2021.10.14  9505868     9609    94569
3  2021.10.13  9505868     9804    77503
4  2021.10.12  9505868    17274   110204

In [7]:
#
df1 = df.drop(columns=['day1sum', 'day1rate', 'day2sum', 'day2rate'], axis=1)
df1.describe()

            subject        day1num        day2num
count  1.790000e+02     179.000000     179.000000
mean   5.086644e+06   40078.150838   34096.636872
std    3.324235e+06   44231.469656   40745.688278
min    1.019322e+06       0.000000       0.000000
25%    2.279241e+06    4385.000000    4794.500000
50%    3.943320e+06   23323.000000   16581.000000
75%    9.505868e+06   71634.500000   50950.000000
max    9.795426e+06  169036.000000  200186.000000

In [9]:
# 기초통계량에 subject 컬럼을 출력하지 않으려면 문자열로 변환
df2 = df1.copy()

In [10]:
df2['subject'] = df2['subject'].astype('str')
df2.head()

         date  subject  day1num  day2num
0  2021.10.16  9505868    10673    66910
1  2021.10.15  9505868    14556   133580
2  2021.10.14  9505868     9609    94569
3  2021.10.13  9505868     9804    77503
4  2021.10.12  9505868    17274   110204

In [11]:
df2.describe()

             day1num        day2num
count     179.000000     179.000000
mean    40078.150838   34096.636872
std     44231.469656   40745.688278
min         0.000000       0.000000
25%      4385.000000    4794.500000
50%     23323.000000   16581.000000
75%     71634.500000   50950.000000
max    169036.000000  200186.000000

In [15]:
# 새로울 열("월")을 생성한 후
df3 = df2.copy()
df3.head()

         date  subject  day1num  day2num
0  2021.10.16  9505868    10673    66910
1  2021.10.15  9505868    14556   133580
2  2021.10.14  9505868     9609    94569
3  2021.10.13  9505868     9804    77503
4  2021.10.12  9505868    17274   110204

In [13]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     179 non-null    object
 1   subject  179 non-null    object
 2   day1num  179 non-null    int64
 3   day2num  179 non-null    int64
dtypes: int64(2), object(2)
memory usage: 5.7+ KB

In [23]:
df3['월'] = df3['date'].str.slice(5, 7)
df3

           date  subject  day1num  day2num   월
0    2021.10.16  9505868    10673    66910  10
1    2021.10.15  9505868    14556   133580  10
2    2021.10.14  9505868     9609    94569  10
3    2021.10.13  9505868     9804    77503  10
4    2021.10.12  9505868    17274   110204  10
..          ...      ...      ...      ...  ..
174  2021.04.25  1023346    23323     3411  04
175  2021.04.24  1023346      200        0  04
176  2021.04.23  1027740    10195      119  04
177  2021.04.22  1023538    27074     2479  04
178  2021.04.21  1019322    22501     2358  04

[179 rows x 5 columns]

In [25]:
# 평균을 출력할 수 있는 열만 선택한 후 평균
df4 = df3[['day1num', 'day2num', '월']]
df4

     day1num  day2num   월
0      10673    66910  10
1      14556   133580  10
2       9609    94569  10
3       9804    77503  10
4      17274   110204  10
..       ...      ...  ..
174    23323     3411  04
175      200        0  04
176    10195      119  04
177    27074     2479  04
178    22501     2358  04

[179 rows x 3 columns]

In [26]:
df4.shape

(179, 3)

In [27]:
df5 = df4.groupby('월').mean()
df5

         day1num       day2num
월
04  22060.100000   2304.600000
05  18225.548387   9734.000000
06  55957.200000  20147.300000
07  25807.870968   9934.903226
08  57667.258065  55575.000000
09  65715.000000  62162.000000
10   9406.312500  79900.750000