In [1]:
# 1. [코로나 이후 국민들이 매체기기 이용량 변화]에 대한 정보를 가지고 있는 데이터파일(covid.csv)을 이용하여 다음 문제를 해결하시오.
# 1) csv 파일을 불러와서 데이터를 확인해보자
# 2) 사례수가 가장 높은 항목의 모든 정보를 출력해보자
# 3) 증가율이 높은 3개의 항목을 출력해보자

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('./input/covid.xlsx')
df.head()

       항목  사례수    증가    감소  변화없음
0    스마트폰  999  78.9   1.7  19.4
1    텔레비전  965  68.5   3.9  27.6
2  개인용 PC  973  65.7   3.7  30.6
3  태블릿 PC  662  46.8   4.2  49.0
4     라디오  687  35.5  12.5  52.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   항목      7 non-null      object
 1   사례수     7 non-null      int64
 2   증가      7 non-null      float64
 3   감소      7 non-null      float64
 4   변화없음    7 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 412.0+ bytes

In [5]:
df.describe()

              사례수         증가         감소       변화없음
count    7.000000   7.000000   7.000000   7.000000
mean   802.000000  49.185714   9.571429  41.242857
std    178.241409  22.506475   8.361362  15.100315
min    552.000000  17.600000   1.700000  19.400000
25%    674.500000  33.400000   3.800000  29.100000
50%    776.000000  46.800000   4.200000  49.000000
75%    969.000000  67.100000  15.150000  51.450000
max    999.000000  78.900000  23.200000  59.200000

In [7]:
max_row = df['사례수'] == df['사례수'].max()
max_row

0     True
1    False
2    False
3    False
4    False
5    False
6    False
Name: 사례수, dtype: bool

In [8]:
df[max_row]

     항목  사례수    증가   감소  변화없음
0  스마트폰  999  78.9  1.7  19.4

In [11]:
df3 = df.sort_values('증가', ascending=False)

In [12]:
df3.head(3)

       항목  사례수    증가   감소  변화없음
0    스마트폰  999  78.9  1.7  19.4
1    텔레비전  965  68.5  3.9  27.6
2  개인용 PC  973  65.7  3.7  30.6

In [13]:
df3.iloc[:3]

       항목  사례수    증가   감소  변화없음
0    스마트폰  999  78.9  1.7  19.4
1    텔레비전  965  68.5  3.9  27.6
2  개인용 PC  973  65.7  3.7  30.6