In [1]:
# 1. 라이브러리 및 데이터 읽어오기

# 2020년 건강검진 일부 데이터 'health_screenings_2020_1000ea.xlsx' 엑셀 파일을 읽어와 동적인 시각화를 표현

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('./input/health_screenings_2020_1000ea.xlsx')
df.head()

,year,city_code,gender,age_code,height,weight,waist,eye_left,eye_right,hear_left,...,serum,AST,ALT,GTP,smoking,drinking,oral_check,dental_caries,tartar,open_date
0,2020,36,1,9,165,60,72.1,1.2,1.5,1,...,1.1,21.0,27.0,21.0,1,0,0,NaN,NaN,2021-12-29
1,2020,27,2,13,150,65,81.0,0.8,0.8,1,...,0.5,18.0,15.0,15.0,1,0,0,NaN,NaN,2021-12-29
2,2020,11,2,12,155,55,70.0,0.6,0.7,1,...,0.7,27.0,25.0,7.0,1,0,0,NaN,NaN,2021-12-29
3,2020,31,1,13,160,70,90.8,1.0,1.0,1,...,1.2,65.0,97.0,72.0,1,0,1,0.0,0.0,2021-12-29
4,2020,41,2,12,155,50,75.2,1.5,1.2,1,...,0.7,18.0,17.0,14.0,1,0,0,NaN,NaN,2021-12-29

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 30 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           1000 non-null   int64
 1   city_code      1000 non-null   int64
 2   gender         1000 non-null   int64
 3   age_code       1000 non-null   int64
 4   height         1000 non-null   int64
 5   weight         1000 non-null   int64
 6   waist          1000 non-null   float64
 7   eye_left       1000 non-null   float64
 8   eye_right      1000 non-null   float64
 9   hear_left      1000 non-null   int64
 10  hear_right     1000 non-null   int64
 11  systolic       991 non-null    float64
 12  diastolic      991 non-null    float64
 13  blood_sugar    991 non-null    float64
 14  cholesterol    401 non-null    float64
 15  triglycerides  401 non-null    float64
 16  HDL            401 non-null    float64
 17  LDL            394 non-null    float64
 18  hemoglobin     991 non-null    float64
 19  urine_protein  987 non-null    float64
 20  serum          991 non-null    float64
 21  AST            991 non-null    float64
 22  ALT            991 non-null    float64
 23  GTP            991 non-null    float64
 24  smoking        1000 non-null   int64
 25  drinking       1000 non-null   int64
 26  oral_check     1000 non-null   int64
 27  dental_caries  306 non-null    float64
 28  tartar         306 non-null    float64
 29  open_date      1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(18), int64(11)
memory usage: 234.5 KB

In [5]:
# 데이터 전처리

# 성별, 음주여부, 흡연산태에 대하여 숫자로 저장되어 있는 정보를 데이터 분석의 가독성을 높이기 위해
# Male, Female, Non-drinking, Drinking, Non-smoking, Smoking의 문자열로 변경하여 데이터 전처리

In [6]:
df1 = df[['gender', 'height', 'weight', 'waist', 'drinking', 'smoking']]
df1.head()

   gender  height  weight  waist  drinking  smoking
0       1     165      60   72.1         0        1
1       2     150      65   81.0         0        1
2       2     155      55   70.0         0        1
3       1     160      70   90.8         0        1
4       2     155      50   75.2         0        1

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   gender    1000 non-null   int64
 1   height    1000 non-null   int64
 2   weight    1000 non-null   int64
 3   waist     1000 non-null   float64
 4   drinking  1000 non-null   int64
 5   smoking   1000 non-null   int64
dtypes: float64(1), int64(5)
memory usage: 47.0 KB

In [8]:
# 성별 데이터를 Male, Female로 변경
df1.value_counts('gender')

gender
2    518
1    482
Name: count, dtype: int64

In [9]:
df1.loc[:, 'gender'] = df1['gender'].astype('object')
df1.loc[df1['gender'] == 1, ['gender']] = 'Male'
df1.loc[df1['gender'] == 2, ['gender']] = 'Female'

C:\Users\kui45\AppData\Local\Temp\ipykernel_20044\4241283683.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 2 2 1 2 1 1 1 2 2 2 2 1 2 2 1 1 2 1 1 1 2 2 1 1 1 1 1 1 2 1 2 2 2 2 2 2
 1 1 2 1 2 2 2 1 1 1 1 1 2 2 2 1 1 2 1 2 2 2 2 2 1 2 2 1 2 2 2 2 2 2 1 1 2
 1 2 1 1 2 2 1 2 2 1 1 2 1 2 2 1 1 1 2 1 1 2 2 2 2 1 2 2 1 2 2 1 1 2 2 2 1
 2 2 2 2 2 2 2 2 1 2 2 1 2 1 1 2 1 1 2 1 1 2 2 2 2 2 2 1 1 1 1 2 1 2 1 1 1
 2 1 2 2 2 2 1 1 2 2 1 2 1 1 2 1 2 1 2 2 2 1 1 1 2 1 2 1 1 1 1 1 1 2 2 1 1
 1 2 2 1 2 1 2 1 1 2 2 2 2 2 2 1 2 2 2 1 1 2 2 2 2 1 1 1 1 1 1 2 2 1 1 1 2
 1 1 1 1 1 1 2 1 2 1 2 2 1 2 2 1 1 1 1 2 2 1 2 1 2 1 1 1 1 2 2 1 1 2 1 1 1
 2 2 1 1 2 2 1 1 2 2 1 2 1 2 1 2 2 2 2 2 1 1 2 2 2 2 2 2 2 1 1 2 2 1 2 1 2
 1 2 2 1 1 2 2 1 1 2 1 2 2 2 1 2 2 1 1 2 1 1 1 1 2 2 2 2 2 1 2 2 1 1 2 1 1
 1 1 1 2 1 2 2 1 1 1 1 2 2 1 2 2 2 1 2 2 2 2 2 2 2 2 2 1 2 1 2 2 1 2 1 1 2
 1 2 2 1 2 1 2 2 2 2 1 1 2 2 1 2 1 2 2 2 2 1 1 1 1 1 1 2 1 2 1 1 2 2 1 1 2
 1 1 1 2 1 2 1 1 1 1 1 1 2 1 2 2 2 2 2 2 2 1 2 2 2 2 2 1 2 2 2 2 2 1 2 1 1
 1 2 2 2 1 2 2 2 1 2 1 2 1 1 1 2 1 1 2 2 1 1 1 1 1 2 1 1 2 1 1 1 1 2 1 1 2
 2 1 2 2 1 2 1 2 1 1 1 2 1 1 1 2 2 1 1 2 2 1 1 2 2 2 1 1 2 1 1 1 2 2 2 2 2
 1 2 2 2 1 2 1 1 1 1 1 2 1 2 2 1 2 2 1 2 1 2 1 2 1 1 1 1 1 2 2 1 1 2 1 2 1
 2 1 2 1 2 1 1 1 2 2 2 2 2 1 1 2 2 2 1 1 2 2 2 2 2 1 1 1 2 2 2 2 2 2 2 1 2
 2 1 2 1 1 2 2 1 1 2 1 1 2 1 2 2 1 1 1 1 2 2 2 2 1 1 2 2 2 1 2 1 2 2 2 2 2
 1 2 2 2 1 1 1 1 1 1 1 2 2 1 2 2 2 2 1 2 2 2 1 1 2 1 2 1 1 2 2 1 2 2 2 1 2
 1 2 1 1 2 2 2 1 1 2 2 1 1 2 1 2 2 1 1 2 1 2 2 2 2 2 1 1 2 1 2 2 2 2 1 1 1
 1 1 1 1 2 1 2 1 2 1 1 1 2 2 1 2 1 1 1 1 2 1 2 1 2 1 2 2 2 1 2 2 2 1 1 1 1
 1 1 1 2 2 1 1 2 2 2 2 1 2 1 1 1 1 1 1 2 1 1 2 1 1 1 2 1 2 1 2 2 2 2 1 2 1
 1 2 2 2 1 2 1 2 2 2 1 2 2 2 1 2 1 2 1 2 2 2 2 1 2 1 2 1 2 1 2 2 1 2 2 2 2
 1 1 1 2 1 1 2 2 1 1 2 1 2 2 1 1 2 1 1 2 1 2 2 2 1 2 2 2 1 1 2 2 1 2 2 2 2
 1 1 2 1 2 1 2 2 1 2 1 2 1 1 2 1 2 1 2 2 1 1 2 1 2 2 1 2 2 2 2 1 2 1 2 1 2
 2 1 1 2 2 1 1 2 1 2 2 1 2 1 1 2 2 1 2 1 2 1 2 1 1 2 2 1 1 1 1 1 1 1 1 2 1
 2 1 2 1 1 2 1 1 2 1 2 1 2 1 1 2 1 2 1 2 2 1 1 1 2 2 2 1 1 2 2 2 2 2 2 1 2
 1 1 1 2 1 2 2 2 1 2 1 1 2 1 2 1 1 2 1 1 2 1 1 1 2 1 1 1 2 1 2 2 1 1 1 2 2
 1]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.loc[:, 'gender'] = df1['gender'].astype('object')

In [10]:
df1.value_counts('gender')

gender
Female    518
Male      482
Name: count, dtype: int64

In [11]:
df1.head()

   gender  height  weight  waist  drinking  smoking
0    Male     165      60   72.1         0        1
1  Female     150      65   81.0         0        1
2  Female     155      55   70.0         0        1
3    Male     160      70   90.8         0        1
4  Female     155      50   75.2         0        1

In [12]:
# 음주 여부 0(비음주)는 Non-drinking, 1(음주)는 Drinking으로 변경
df1.value_counts('drinking')

drinking
1    569
0    431
Name: count, dtype: int64

In [13]:
df1.loc[df1['drinking'] == 0, ['drinking']] = 'Non-drinking'
df1.loc[df1['drinking'] == 1, ['drinking']] = 'Drinking'

C:\Users\kui45\AppData\Local\Temp\ipykernel_20044\1560699482.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Non-drinking' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.loc[df1['drinking'] == 0, ['drinking']] = 'Non-drinking'

In [14]:
df1.value_counts('drinking')

drinking
Drinking        569
Non-drinking    431
Name: count, dtype: int64

In [15]:
# 흡연상태 1(비흡연)과 2(흡연 끊음)은 Non-smoking, 3(흡연)은 Smoking으로 변경
df1.value_counts('smoking')

smoking
1    633
2    188
3    179
Name: count, dtype: int64

In [16]:
df1.loc[df1['smoking'] == 1, ['smoking']] = 'Non-smoking'
df1.loc[df1['smoking'] == 2, ['smoking']] = 'Non-smoking'
df1.loc[df1['smoking'] == 3, ['smoking']] = 'Smoking'

C:\Users\kui45\AppData\Local\Temp\ipykernel_20044\433003436.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Non-smoking' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.loc[df1['smoking'] == 1, ['smoking']] = 'Non-smoking'

In [17]:
df1.value_counts('smoking')

smoking
Non-smoking    821
Smoking        179
Name: count, dtype: int64

In [18]:
df1.head()

   gender  height  weight  waist      drinking      smoking
0    Male     165      60   72.1  Non-drinking  Non-smoking
1  Female     150      65   81.0  Non-drinking  Non-smoking
2  Female     155      55   70.0  Non-drinking  Non-smoking
3    Male     160      70   90.8  Non-drinking  Non-smoking
4  Female     155      50   75.2  Non-drinking  Non-smoking

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   gender    1000 non-null   object
 1   height    1000 non-null   int64
 2   weight    1000 non-null   int64
 3   waist     1000 non-null   float64
 4   drinking  1000 non-null   object
 5   smoking   1000 non-null   object
dtypes: float64(1), int64(2), object(3)
memory usage: 47.0+ KB

In [20]:
# 데이터를 저장

df1.to_pickle('./output/health_screenings_2020_1000ea.pkl')